name: PlatformIO CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: [00_Blink, 02_CAN_Counter, 04_CAN_MultiMessages, 01_CAN_Send, 03_CAN_Buttons_Analog, 05_CAN_6Button_Sender]
        environment: [uno, nano]
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install platformio
    - name: Run PlatformIO
      run: |
        platformio run --project-dir ${{ matrix.project }} --environment  ${{ matrix.board }}
    - uses: actions/upload-artifact@v2
      with:
        name: firmware
        path: ./*/.pio/build/*/firmware.*
